// Generated by CoffeeScript 1.7.1
(function() {
  var getHttpRequest, httpRequest, resourceUrl;

  resourceUrl = 'http://localhost:3000/students';

  getHttpRequest = (function() {
    var xmlHttpFactories;
    xmlHttpFactories = [
      function() {
        return new XMLHttpRequest();
      }, function() {
        return new ActiveXObject('Msxml3.XMLHTTP');
      }, function() {
        return new ActiveXObject('Msxml2.XMLHTTP.6.0');
      }, function() {
        return new ActiveXObject('Msxml2.XMLHTTP.3.0');
      }, function() {
        return new ActiveXObject('Msxml2.XMLHTTP');
      }, function() {
        return new ActiveXObject('Microsoft.XMLHTTP');
      }
    ];
    return function() {
      var xmlFactory, _i, _len;
      for (_i = 0, _len = xmlHttpFactories.length; _i < _len; _i++) {
        xmlFactory = xmlHttpFactories[_i];
        try {
          return xmlFactory();
        } catch (_error) {

        }
      }
      return null;
    };
  })();

  httpRequest = getHttpRequest();

  httpRequest.onreadystatechange = function() {
    if (httpRequest.readyState === 4) {
      switch (Math.floor(httpRequest.status / 100)) {
        case 2:
          return document.getElementById('http-response').innerHTML = httpRequest.responseText;
        default:
          return document.getElementById('http-response'.innerHTML = '<div><h1 style="color:#f00">Error happened</h1>#{httpRequest.responseText}</div>');
      }
    }
  };

  httpRequest.open('GET', 'partial.html', true);

  httpRequest.setRequestHeader('Content-type', 'application/json');

  httpRequest.send(null);

}).call(this);

//# sourceMappingURL=response-html.map
